/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PathwaysRouteImport } from './routes/pathways'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PathwayAnaemiaRouteImport } from './routes/pathway.anaemia'

const PathwaysRoute = PathwaysRouteImport.update({
  id: '/pathways',
  path: '/pathways',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathwayAnaemiaRoute = PathwayAnaemiaRouteImport.update({
  id: '/pathway/anaemia',
  path: '/pathway/anaemia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pathways': typeof PathwaysRoute
  '/pathway/anaemia': typeof PathwayAnaemiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pathways': typeof PathwaysRoute
  '/pathway/anaemia': typeof PathwayAnaemiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pathways': typeof PathwaysRoute
  '/pathway/anaemia': typeof PathwayAnaemiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/pathways' | '/pathway/anaemia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/pathways' | '/pathway/anaemia'
  id: '__root__' | '/' | '/about' | '/pathways' | '/pathway/anaemia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PathwaysRoute: typeof PathwaysRoute
  PathwayAnaemiaRoute: typeof PathwayAnaemiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pathways': {
      id: '/pathways'
      path: '/pathways'
      fullPath: '/pathways'
      preLoaderRoute: typeof PathwaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathway/anaemia': {
      id: '/pathway/anaemia'
      path: '/pathway/anaemia'
      fullPath: '/pathway/anaemia'
      preLoaderRoute: typeof PathwayAnaemiaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PathwaysRoute: PathwaysRoute,
  PathwayAnaemiaRoute: PathwayAnaemiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
