/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PathwaysRouteImport } from './routes/pathways'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PathwaysLocationRouteImport } from './routes/pathways.$location'
import { Route as PathwayLftRouteImport } from './routes/pathway.lft'
import { Route as PathwayAnaemiaRouteImport } from './routes/pathway.anaemia'
import { Route as PathwaysLocationPathwayRouteImport } from './routes/pathways.$location.$pathway'
import { Route as PathwaysLocationPathwayVariantRouteImport } from './routes/pathways.$location.$pathway.$variant'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PathwaysRoute = PathwaysRouteImport.update({
  id: '/pathways',
  path: '/pathways',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathwaysLocationRoute = PathwaysLocationRouteImport.update({
  id: '/$location',
  path: '/$location',
  getParentRoute: () => PathwaysRoute,
} as any)
const PathwayLftRoute = PathwayLftRouteImport.update({
  id: '/pathway/lft',
  path: '/pathway/lft',
  getParentRoute: () => rootRouteImport,
} as any)
const PathwayAnaemiaRoute = PathwayAnaemiaRouteImport.update({
  id: '/pathway/anaemia',
  path: '/pathway/anaemia',
  getParentRoute: () => rootRouteImport,
} as any)
const PathwaysLocationPathwayRoute = PathwaysLocationPathwayRouteImport.update({
  id: '/$pathway',
  path: '/$pathway',
  getParentRoute: () => PathwaysLocationRoute,
} as any)
const PathwaysLocationPathwayVariantRoute =
  PathwaysLocationPathwayVariantRouteImport.update({
    id: '/$variant',
    path: '/$variant',
    getParentRoute: () => PathwaysLocationPathwayRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pathways': typeof PathwaysRouteWithChildren
  '/results': typeof ResultsRoute
  '/pathway/anaemia': typeof PathwayAnaemiaRoute
  '/pathway/lft': typeof PathwayLftRoute
  '/pathways/$location': typeof PathwaysLocationRouteWithChildren
  '/pathways/$location/$pathway': typeof PathwaysLocationPathwayRouteWithChildren
  '/pathways/$location/$pathway/$variant': typeof PathwaysLocationPathwayVariantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pathways': typeof PathwaysRouteWithChildren
  '/results': typeof ResultsRoute
  '/pathway/anaemia': typeof PathwayAnaemiaRoute
  '/pathway/lft': typeof PathwayLftRoute
  '/pathways/$location': typeof PathwaysLocationRouteWithChildren
  '/pathways/$location/$pathway': typeof PathwaysLocationPathwayRouteWithChildren
  '/pathways/$location/$pathway/$variant': typeof PathwaysLocationPathwayVariantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pathways': typeof PathwaysRouteWithChildren
  '/results': typeof ResultsRoute
  '/pathway/anaemia': typeof PathwayAnaemiaRoute
  '/pathway/lft': typeof PathwayLftRoute
  '/pathways/$location': typeof PathwaysLocationRouteWithChildren
  '/pathways/$location/$pathway': typeof PathwaysLocationPathwayRouteWithChildren
  '/pathways/$location/$pathway/$variant': typeof PathwaysLocationPathwayVariantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/pathways'
    | '/results'
    | '/pathway/anaemia'
    | '/pathway/lft'
    | '/pathways/$location'
    | '/pathways/$location/$pathway'
    | '/pathways/$location/$pathway/$variant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/pathways'
    | '/results'
    | '/pathway/anaemia'
    | '/pathway/lft'
    | '/pathways/$location'
    | '/pathways/$location/$pathway'
    | '/pathways/$location/$pathway/$variant'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/pathways'
    | '/results'
    | '/pathway/anaemia'
    | '/pathway/lft'
    | '/pathways/$location'
    | '/pathways/$location/$pathway'
    | '/pathways/$location/$pathway/$variant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PathwaysRoute: typeof PathwaysRouteWithChildren
  ResultsRoute: typeof ResultsRoute
  PathwayAnaemiaRoute: typeof PathwayAnaemiaRoute
  PathwayLftRoute: typeof PathwayLftRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathways': {
      id: '/pathways'
      path: '/pathways'
      fullPath: '/pathways'
      preLoaderRoute: typeof PathwaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathways/$location': {
      id: '/pathways/$location'
      path: '/$location'
      fullPath: '/pathways/$location'
      preLoaderRoute: typeof PathwaysLocationRouteImport
      parentRoute: typeof PathwaysRoute
    }
    '/pathway/lft': {
      id: '/pathway/lft'
      path: '/pathway/lft'
      fullPath: '/pathway/lft'
      preLoaderRoute: typeof PathwayLftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathway/anaemia': {
      id: '/pathway/anaemia'
      path: '/pathway/anaemia'
      fullPath: '/pathway/anaemia'
      preLoaderRoute: typeof PathwayAnaemiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathways/$location/$pathway': {
      id: '/pathways/$location/$pathway'
      path: '/$pathway'
      fullPath: '/pathways/$location/$pathway'
      preLoaderRoute: typeof PathwaysLocationPathwayRouteImport
      parentRoute: typeof PathwaysLocationRoute
    }
    '/pathways/$location/$pathway/$variant': {
      id: '/pathways/$location/$pathway/$variant'
      path: '/$variant'
      fullPath: '/pathways/$location/$pathway/$variant'
      preLoaderRoute: typeof PathwaysLocationPathwayVariantRouteImport
      parentRoute: typeof PathwaysLocationPathwayRoute
    }
  }
}

interface PathwaysLocationPathwayRouteChildren {
  PathwaysLocationPathwayVariantRoute: typeof PathwaysLocationPathwayVariantRoute
}

const PathwaysLocationPathwayRouteChildren: PathwaysLocationPathwayRouteChildren =
  {
    PathwaysLocationPathwayVariantRoute: PathwaysLocationPathwayVariantRoute,
  }

const PathwaysLocationPathwayRouteWithChildren =
  PathwaysLocationPathwayRoute._addFileChildren(
    PathwaysLocationPathwayRouteChildren,
  )

interface PathwaysLocationRouteChildren {
  PathwaysLocationPathwayRoute: typeof PathwaysLocationPathwayRouteWithChildren
}

const PathwaysLocationRouteChildren: PathwaysLocationRouteChildren = {
  PathwaysLocationPathwayRoute: PathwaysLocationPathwayRouteWithChildren,
}

const PathwaysLocationRouteWithChildren =
  PathwaysLocationRoute._addFileChildren(PathwaysLocationRouteChildren)

interface PathwaysRouteChildren {
  PathwaysLocationRoute: typeof PathwaysLocationRouteWithChildren
}

const PathwaysRouteChildren: PathwaysRouteChildren = {
  PathwaysLocationRoute: PathwaysLocationRouteWithChildren,
}

const PathwaysRouteWithChildren = PathwaysRoute._addFileChildren(
  PathwaysRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PathwaysRoute: PathwaysRouteWithChildren,
  ResultsRoute: ResultsRoute,
  PathwayAnaemiaRoute: PathwayAnaemiaRoute,
  PathwayLftRoute: PathwayLftRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
